"""add channel links

Revision ID: 315c19dda564
Revises: 8f656be3110f
Create Date: 2026-08-18 21:42:46.452175

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '315c19dda564'
down_revision: Union[str, None] = '8f656be3110f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_link_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', name='channel_type'), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_channel_link_codes_code', 'channel_link_codes', ['code'], unique=True)
    op.create_table('user_channel_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'whatsapp', name='channel_type'), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('linked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel', 'channel_id', name='uq_channel_link_channel_id')
    )
    op.create_index('ix_channel_link_user_id', 'user_channel_links', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # Nota: autogenerate volvió a detectar 'uq_user_category_config' y
    # 'uq_user_income_type_config' como "faltantes" — mismo drift preexistente
    # ya documentado en 8f656be3110f_add_merchant_category_memory.py, no
    # relacionado con esta feature. Se deja fuera deliberadamente.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_channel_link_user_id', table_name='user_channel_links')
    op.drop_table('user_channel_links')
    op.drop_index('ix_channel_link_codes_code', table_name='channel_link_codes')
    op.drop_table('channel_link_codes')
    # ### end Alembic commands ###
