"""add merchant category memory

Revision ID: 8f656be3110f
Revises: a4b5c6d7e8f9
Create Date: 2026-08-18 20:00:12.773499

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8f656be3110f'
down_revision: Union[str, None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_category_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('merchant_keyword', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'merchant_keyword', name='uq_merchant_memory_user_keyword')
    )
    op.create_index('ix_merchant_memory_user_id', 'merchant_category_memory', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # Nota: autogenerate también detectó 'uq_user_category_config' y
    # 'uq_user_income_type_config' como constraints "faltantes" — es drift
    # preexistente entre el modelo y la BD, no relacionado con esta feature.
    # Se deja fuera deliberadamente; investigar por separado si hace falta.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_merchant_memory_user_id', table_name='merchant_category_memory')
    op.drop_table('merchant_category_memory')
    # ### end Alembic commands ###
